# Generated by Django 5.1.4 on 2025-04-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0004_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
