# Generated by Django 4.2.4 on 2025-01-10 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_office_division_college', models.CharField(max_length=200)),
                ('operating_unit_project', models.CharField(max_length=200)),
                ('property_number', models.CharField(max_length=100)),
                ('responsible_person', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('date_acquired', models.DateField()),
                ('fund', models.CharField(max_length=100)),
                ('ppe_class', models.CharField(max_length=100)),
                ('estimated_useful_life', models.IntegerField(help_text='Estimated useful life in years')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.itemtype')),
            ],
        ),
    ]
