# Generated by Django 4.2.4 on 2025-01-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_types/'),
        ),
    ]
