# Generated by Django 5.1.4 on 2025-01-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_item_is_archived_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='responsible_person',
            field=models.CharField(default='BAWANG, Rex John G.', max_length=200),
        ),
    ]
