# Generated by Django 5.1.4 on 2025-01-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
