# Generated by Django 5.1.4 on 2025-01-22 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_item_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Australia', 'Australia'), ('Antarctica', 'Antarctica')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('partner', models.CharField(max_length=255)),
                ('type_of_organization', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='partnership_files/')),
                ('description', models.TextField(blank=True, null=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='administrator.partnership')),
            ],
        ),
    ]
