# Generated by Django 5.1.4 on 2025-01-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_partnership_partnershipfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_logos/'),
        ),
    ]
