# Generated by Django 5.1.4 on 2025-01-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_partnership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='is_removed_from_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='ppe_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        migrations.AlterField(
            model_name='partnership',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('South East Asia', 'South East Asia'), ('South Asia', 'South Asia'), ('East Asia', 'East Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Australia', 'Australia'), ('Antarctica', 'Antarctica')], max_length=50),
        ),
    ]
