# Generated by Django 5.1.4 on 2025-01-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_remove_partnership_is_removed_from_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='property_number',
            field=models.CharField(max_length=100),
        ),
    ]
