# Generated by Django 5.1.4 on 2025-01-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_alter_item_property_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='is_removed_from_list',
            field=models.BooleanField(default=False),
        ),
    ]
