# Generated by Django 5.1.4 on 2025-01-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_partnership_is_removed_from_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('Common Supplies and Equipment Available at PS-DBM', 'Common Supplies and Equipment Available at PS-DBM'), ('Other Items not available at PS DBM but regularly purchased from other sources', 'Other Items not available at PS DBM but regularly purchased from other sources'), ('Other Supplies and Materials', 'Other Supplies and Materials'), ('Services, Rentals, and Others', 'Services, Rentals, and Others'), ('Capital Outlay', 'Capital Outlay')], max_length=200)),
                ('expenditure_type', models.CharField(max_length=200)),
                ('item_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('mode_of_procurement', models.CharField(max_length=200)),
                ('quarter1', models.PositiveIntegerField(default=0)),
                ('quarter2', models.PositiveIntegerField(default=0)),
                ('quarter3', models.PositiveIntegerField(default=0)),
                ('quarter4', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('unit_of_measure', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
