# Generated by Django 5.1.4 on 2025-01-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='year',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
