# Generated by Django 5.1.4 on 2025-01-30 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_alter_expenditure_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.year'),
        ),
    ]
