# Generated by Django 5.1.4 on 2025-01-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_year_alter_expenditure_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='year',
        ),
    ]
