# Generated by Django 5.1.4 on 2025-01-30 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_remove_expenditure_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='year',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='administrator.year'),
            preserve_default=False,
        ),
    ]
