# Generated by Django 5.1.4 on 2025-01-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_remove_expenditure_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
