# Generated by Django 5.1.4 on 2025-01-30 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_expenditure_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.year'),
        ),
    ]
