# Generated by Django 5.1.4 on 2025-02-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_alter_expenditure_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='url',
            field=models.URLField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='classification',
            field=models.CharField(choices=[('Other Items not available at PS DBM but regularly purchased from other sources', 'Other Items not available at PS DBM but regularly purchased from other sources'), ('Other Supplies and Materials', 'Other Supplies and Materials'), ('Services, Rentals, and Others', 'Services, Rentals, and Others'), ('Capital Outlay', 'Capital Outlay')], max_length=200),
        ),
    ]
