# Generated by Django 5.1.4 on 2025-03-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_partnership_url_alter_expenditure_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Center A', 'Center A'), ('Center B', 'Center B'), ('Center C', 'Center C')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Office 1', 'Office 1'), ('Office 2', 'Office 2'), ('Office 3', 'Office 3')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Visit', 'Visit'), ('Study Tour', 'Study Tour'), ('Interview', 'Interview')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Research and Extension', 'Research and Extension'), ('Administration and Finance', 'Administration and Finance'), ('Academic', 'Academic')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Germany', 'Germany')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(choices=[(2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')])),
                ('center_unit', models.ManyToManyField(related_name='centers', to='administrator.center')),
                ('office_college', models.ManyToManyField(related_name='offices', to='administrator.office')),
                ('purpose', models.ManyToManyField(related_name='purposes', to='administrator.purpose')),
                ('sector_visited', models.ManyToManyField(related_name='sectors', to='administrator.sector')),
            ],
        ),
    ]
