# Generated by Django 5.1.4 on 2025-03-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_alter_internationalvisitor_center_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
