# Generated by Django 5.1.4 on 2025-03-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_center_abbreviation_office_abbreviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
