# Generated by Django 5.1.4 on 2025-04-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_year_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalvisitor',
            name='purpose',
        ),
        migrations.AddField(
            model_name='internationalvisitor',
            name='purpose',
            field=models.TextField(blank=True, max_length=510),
        ),
    ]
