from django.urls import path
from . import views



urlpatterns = [
    path('', views.administrator_dashboard, name="administrator_dashboard"),
    path('items/', views.item_list, name='item_list'),
    path('item-types/', views.item_type_list, name='item_type_list'),
    path('item-types/<int:pk>/edit/', views.edit_item_type, name='edit_item_type'),
    path('item-types/<int:pk>/delete/', views.delete_item_type, name='delete_item_type'),
    path('item-admin/<int:id>/', views.item_detail, name='item_detail_admin'),
    path('item/edit/<int:id>/', views.item_edit, name='item_edit'),
    path('item/<int:id>/add-image/', views.add_item_image, name='add_item_image'),
    path('item/<int:id>/edit-image/', views.edit_item_image, name='edit_item_image'),
    path('item/<int:id>/delete-image/', views.delete_item_image, name='delete_item_image'),
    path('export-items/', views.export_items_to_excel, name='export_items'),
    path('item/archive/<int:item_id>/', views.archive_item, name='item_archive'),
    path('export_items/', views.export_items_to_pdf, name='export_items_to_pdf'),
    path('archived-items/', views.archived_items_view, name='archived_items'),
    path('item/<int:item_id>/unarchive/', views.unarchive_item, name='unarchive_item'),
    path('download-db-backup/', views.download_db_backup, name='download_db_backup'),
    path('restore_database/', views.restore_database, name='restore_database'),
    path('account-logout/', views.logout_view, name="logout_route"),
    path('partnerships/', views.partnership_list, name='partnership_list'),
    path('partnership/<int:partnership_id>/', views.partnership_detail, name='partnership_detail'),
    path('partnerships/<int:partnership_id>/upload-file/', views.upload_file_to_partnership, name='upload_file_to_partnership'),
    path('administrator/delete-partnership-file/', views.delete_partnership_file, name='delete_partnership_file'),
    path('expenditures/', views.expenditure_list, name="expenditures_list"),
    path('year/<int:year_id>/add-expenditure/', views.add_expenditure, name='add_expenditure'),
    path('years/', views.year_list, name='year_list'),
    path('years/<int:year_id>/', views.year_detail, name='year_detail'),
    path('partnership/<int:partnership_id>/remove/', views.remove_partnership, name='remove_partnership'),
    path('removed_partnerships/', views.removed_partnerships_view, name='removed_partnerships'),
    path('partnerships/<int:partnership_id>/edit/', views.edit_partnership, name='edit_partnership'),
    path("delete-expenditure/<int:expenditure_id>/", views.delete_expenditure, name="delete_expenditure"),
    path('visitors/', views.visitor_list, name='visitor_list'),
    path('add-visitor/', views.add_visitor, name='add_visitor'),
    path('edit-visitor/', views.edit_visitor, name='edit_visitor'),
    path('delete-visitor/<int:visitor_id>/', views.delete_visitor, name='delete_visitor'),
    path('export-international-visitors-excel/', views.export_international_visitors_to_excel, name='export_international_visitors_to_excel'),
    path("rooms/", views.list_of_rooms, name="list_of_rooms"),
    path("add-room/", views.add_room, name="add_room"),
    path("delete-room/<int:room_id>/", views.delete_room, name="delete_room"),
    path('room/edit/<int:room_id>/', views.edit_room, name='edit_room'),
    path('years/add/', views.add_year, name='add_year'),
    path('delete-year/<int:year_id>/', views.delete_year, name='delete_year'),
    path("edit-year/", views.edit_year, name="edit_year"),
    path('expenditure/edit/<int:expenditure_id>/', views.edit_expenditure, name='edit_expenditure'),
    path('approve-reservation/', views.approve_reservation, name='approve_reservation'),
    path('confirmed-reservations/', views.confirmed_reservations, name='confirmed_reservations'),
    path('cancel-reservation/', views.cancel_reservation, name='cancel_reservation'),
    path('cancel-confirmed-reservation/', views.cancel_confirmed_reservation, name='cancel_confirmed_reservation'),
    path('cancelled-reservations/', views.cancelled_reservations_view, name='cancelled_reservations'),
    path('completed-reservations/', views.completed_reservations, name='completed_reservations'),
    path("pending-reservations/", views.pending_reservations, name="pending_reservations"),
     path('complete-reservation/', views.complete_reservation, name='complete_reservation'),
]
    

